// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARoAT1uPpK6rlh1lqp0eScGE3Yh8xWoDg',
    appId: '1:318936986508:web:a88a064ee660a639f91ca9',
    messagingSenderId: '318936986508',
    projectId: 'church-management-system-d3836',
    authDomain: 'church-management-system-d3836.firebaseapp.com',
    storageBucket: 'church-management-system-d3836.firebasestorage.app',
    measurementId: 'G-1DZRCNWEK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj3IUNVvlP1cD08g_cCAfGNNGgKxjX6KI',
    appId: '1:318936986508:android:025eb16149db8028f91ca9',
    messagingSenderId: '318936986508',
    projectId: 'church-management-system-d3836',
    storageBucket: 'church-management-system-d3836.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2-7BL1SL_bn1O8R9vzmiCzfxN8U8LC4Y',
    appId: '1:318936986508:ios:0006f64a42551369f91ca9',
    messagingSenderId: '318936986508',
    projectId: 'church-management-system-d3836',
    storageBucket: 'church-management-system-d3836.firebasestorage.app',
    iosClientId:
        '318936986508-vun5e3s0ae6jrj8j3l2t5us3jdiei0l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchManagementMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2-7BL1SL_bn1O8R9vzmiCzfxN8U8LC4Y',
    appId: '1:318936986508:ios:0006f64a42551369f91ca9',
    messagingSenderId: '318936986508',
    projectId: 'church-management-system-d3836',
    storageBucket: 'church-management-system-d3836.firebasestorage.app',
    iosClientId:
        '318936986508-vun5e3s0ae6jrj8j3l2t5us3jdiei0l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchManagementMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARoAT1uPpK6rlh1lqp0eScGE3Yh8xWoDg',
    appId: '1:318936986508:web:f9e400eda7d5720df91ca9',
    messagingSenderId: '318936986508',
    projectId: 'church-management-system-d3836',
    authDomain: 'church-management-system-d3836.firebaseapp.com',
    storageBucket: 'church-management-system-d3836.firebasestorage.app',
    measurementId: 'G-Y58HQGDJ4N',
  );
}
